# .github/workflows/greetings.yml
name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.TOKEN }}
          issue-message: "Woohoo! Your first ever issue with us in this repository has been created🎊🎊!!"
          pr-message: "Perfection! Advancing through the open-source world!🎊🎊 :) Please be patient while our maintainers and reviewers check the code."
